# ---------------------------------------------
# Namespace (optional)
# ---------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
# ---------------------------------------------
# DaemonSet: runs one NRPE pod per node
# ---------------------------------------------
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nrpe
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: nrpe
  template:
    metadata:
      labels:
        app: nrpe
    spec:
      tolerations:
        - key: "infra"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: nrpe
          image: syedkashif5/nagios-nrpe:2.0
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/nagios/bin/nrpe"]
          args: ["-c", "/usr/local/nagios/etc/nrpe.cfg", "-f"]
          ports:
            - name: nrpe
              containerPort: 5666
              hostPort: 5666
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 5666
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5666
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          securityContext:
            privileged: true
          volumeMounts:
            - name: proc
              mountPath: /proc
              readOnly: true
            - name: utmp
              mountPath: /var/run/utmp
              readOnly: true
            - name: rootfs
              mountPath: /host/root
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: utmp
          hostPath:
            path: /var/run/utmp
        - name: rootfs
          hostPath:
            path: /
---
# ---------------------------------------------
# NetworkPolicy: allow only Nagios server(s)
# ---------------------------------------------
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nagios-to-nrpe
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app: nrpe
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 65.108.87.154/32
      ports:
        - protocol: TCP
          port: 5666
